

-- Crear tabla repartidor

CREATE TABLE repartidor (
  -- Mantenemos el UUID como Primary Key para mejor seguridad y escalabilidad
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    
  -- Nombre	
  nombre TEXT,
  -- Apellido
  apellido TEXT,
  
  -- Usamos now() para que la fecha se asigne automáticamente al crear el registro
  fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT now(),
    
  -- Relación con la tabla profiles
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Documento de identidad 
  cedula text not null
  
  
);



ALTER TABLE repartidor ENABLE ROW LEVEL SECURITY;

-- El dueño del negocio puede ver, crear, editar y borrar sus propios repartidores
CREATE POLICY "Gestión total de repartidores para el dueño"
ON repartidor
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);


-- Política para que el dueño pueda asignar un repartidor a un pedido
-- Solo si el repartidor_id pertenece al catálogo del mismo dueño
CREATE POLICY "Asignar solo repartidores propios a pedidos"
ON pedido
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (
  repartidor_id IS NULL OR 
  EXISTS (
    SELECT 1 FROM repartidor 
    WHERE repartidor.id = pedido.repartidor_id 
    AND repartidor.user_id = auth.uid()
  )
);


-- 2. Política de Inserción
CREATE POLICY "Usuarios pueden crear sus propios pedidos"
ON pedido
FOR INSERT
WITH CHECK (auth.uid() = user_id);


-- Crear tabla de articulos

CREATE TABLE articulo (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  descripcion TEXT not null,
  cantidad INTEGER not null,
  precio INTEGER not null,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  pedido_id UUID NOT NULL REFERENCES pedido(id) ON DELETE CASCADE
  
);


CREATE INDEX idx_articulo_pedido_id ON articulo(pedido_id);




CREATE TYPE estado_pedido AS ENUM ('pendiente', 'en-proceso', 'completado', 'cancelado');

-- 2. Crear la tabla pedido
CREATE TABLE pedido (
  -- Mantenemos el UUID como Primary Key para mejor seguridad y escalabilidad
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  
  -- id_pedido como entero, autoincremental y único
  id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  
  descripcion TEXT,
  direccion TEXT,
  estado estado_pedido DEFAULT 'pendiente',
  
  -- Usamos now() para que la fecha se asigne automáticamente al crear el registro
  fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT now(),
  fecha_terminacion TIMESTAMP WITH TIME ZONE,
  
  -- Relación con la tabla profiles
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE
  
  --relacion tabla repartidor
  repartidor_id UUID REFERENCES repartidor(id) ON DELETE SET NULL
);


ALTER TABLE pedido ENABLE ROW LEVEL SECURITY;

-- Ejemplo: Permitir que los usuarios vean solo sus propios pedidos
CREATE POLICY "Permitir que los usuarios vean solo sus propios pedidos" 
ON pedido FOR SELECT 
USING (auth.uid() = user_id);



ALTER TABLE pedido ENABLE ROW LEVEL SECURITY;

-- Ejemplo: Permitir que los usuarios vean solo sus propios pedidos
CREATE POLICY "Permitir que los usuarios vean solo sus propios pedidos" 
ON repartidor FOR SELECT 
USING (auth.uid() = user_id);

