

-- Crear tabla repartidor

CREATE TABLE repartidor (
  -- Mantenemos el UUID como Primary Key para mejor seguridad y escalabilidad
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    
  -- Nombre	
  nombre TEXT,
  -- Apellido
  apellido TEXT,
  
  -- Usamos now() para que la fecha se asigne automáticamente al crear el registro
  fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT now(),
    
  -- Relación con la tabla profiles
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Documento de identidad 
  cedula text not null
);



-- Crear tabla de articulos

CREATE TABLE articulo (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  descripcion TEXT not null,
  cantidad INTEGER not null,
  precio INTEGER not null,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  pedido_id UUID NOT NULL REFERENCES pedido(id) ON DELETE CASCADE
  
);


CREATE INDEX idx_articulo_pedido_id ON articulo(pedido_id);




CREATE TYPE estado_pedido AS ENUM ('pendiente', 'en-proceso', 'completado', 'cancelado');

-- 2. Crear la tabla pedido
CREATE TABLE pedido (
  -- Mantenemos el UUID como Primary Key para mejor seguridad y escalabilidad
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  
  -- id_pedido como entero, autoincremental y único
  id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  
  descripcion TEXT,
  estado estado_pedido DEFAULT 'pendiente',
  
  -- Usamos now() para que la fecha se asigne automáticamente al crear el registro
  fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT now(),
  fecha_terminacion TIMESTAMP WITH TIME ZONE,
  
  -- Relación con la tabla profiles
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE
);


ALTER TABLE pedido ENABLE ROW LEVEL SECURITY;

-- Ejemplo: Permitir que los usuarios vean solo sus propios pedidos
CREATE POLICY "Permitir que los usuarios vean solo sus propios pedidos" 
ON pedido FOR SELECT 
USING (auth.uid() = user_id);



ALTER TABLE pedido ENABLE ROW LEVEL SECURITY;

-- Ejemplo: Permitir que los usuarios vean solo sus propios pedidos
CREATE POLICY "Permitir que los usuarios vean solo sus propios pedidos" 
ON repartidor FOR SELECT 
USING (auth.uid() = user_id);

